## 行列演算の基礎

- ベクトルの定義
- 行列の定義
- 転置
- 逆行列
- 行列積

In [1]:
import numpy as np

In [2]:
# ベクトルの定義
x=np.array([[1],[2],[3]])
print(x)

[[1]
 [2]
 [3]]


In [3]:
#行列の定義
X=np.array([[1,2],[3,4]])
print(X)

[[1 2]
 [3 4]]


In [4]:
#転置
Xt=X.T
print(Xt)

[[1 3]
 [2 4]]


In [5]:
#逆行列
#linear algebra:線形代数
X_inv=np.linalg.inv(X)
print(X_inv)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [6]:
#行列積
XX_inv=np.dot(X,X_inv)
print(XX_inv)

[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


## 演習問題

In [8]:
#Xの定義
X=np.array([[1,2,3],[1,2,5],[1,3,4],[1,5,9]])
X

array([[1, 2, 3],
       [1, 2, 5],
       [1, 3, 4],
       [1, 5, 9]])

In [9]:
#yの定義
y=np.array([
    [1],
    [5],
    [6],
    [8]
])
y

array([[1],
       [5],
       [6],
       [8]])

In [10]:
#Step1
XtX=np.dot(X.T,X)
XtX

array([[  4,  12,  21],
       [ 12,  42,  73],
       [ 21,  73, 131]])

In [11]:
#Step2
XtX_inv=np.linalg.inv(XtX)
XtX_inv

array([[ 1.76530612, -0.39795918, -0.06122449],
       [-0.39795918,  0.84693878, -0.40816327],
       [-0.06122449, -0.40816327,  0.24489796]])

In [12]:
#Step3
Xty=np.dot(X.T,y)
Xty

array([[ 20],
       [ 70],
       [124]])

In [13]:
#Step4
w=np.dot(XtX_inv,Xty)
w

array([[-0.14285714],
       [ 0.71428571],
       [ 0.57142857]])

In [14]:
import sklearn

In [16]:
#重回帰分析の読み込み
from sklearn.linear_model import LinearRegression

In [22]:
#モデルの宣言
model=LinearRegression(fit_intercept=False)

In [24]:
#モデルの学習←パラメータの調整
model.fit(X,y)

LinearRegression(copy_X=True, fit_intercept=False, n_jobs=1, normalize=False)

In [25]:
#調整後のパラメータ
model.coef_

array([[-0.14285714,  0.71428571,  0.57142857]])

In [26]:
model.intercept_

0.0

In [27]:
#予測精度←決定係数
model.score(X,y)

0.6923076923076924

In [28]:
#予測値の計算
x=np.array([[1,2,3]])

In [31]:
y_pred=model.predict(x)
y_pred

array([[3.]])